Schema for Product, Contact, Navigation
merchantly/front-public pull request #205
Opened 2021-02-14 22:54 UTC by klondaiker

2021-02-15 06:56 UTC, dapi commented on app/scripts/lib/datesHelper.js
> +}
А что такое 1000? Почему именно 1000? 

Завтра можно считать проще:

```
var tomorrow = new Date();
tomorrow.setDate(new Date().getDate()+1);
```

2021-02-15 07:01 UTC, dapi requested changes

2021-02-15 07:01 UTC, dapi commented on app/scripts/react/components/Product/ProductBlock/index.js
> +        <meta itemProp="priceValidUntil" content={tomorrowDate().toJSON().slice(0,10)} />
Если хочешь вывести дату в формате ISO 8601, то используй `date.toISOString(); //"2011-12-19T15:28:46.493Z"`

2021-02-15 08:46 UTC, klondaiker commented on app/scripts/lib/datesHelper.js
> +}
У вас выдает число а не дату
tomorrow.setDate(new Date().getDate()+1)
=> 1613464789663
Придется делать
new Date(today.setDate(new Date().getDate()+1));
Так что тут спорно чье решение выразительнее
1000 - милисекунды

2021-02-15 14:50 UTC, klondaiker commented on app/scripts/lib/datesHelper.js
> +}
В итоге пока убрал priceValidUntil

2021-02-24 04:53 UTC, dapi commented
Вливаем?

2021-02-24 07:28 UTC, dapi commented on app/scripts/lib/datesHelper.js
> +}
Жуть какая ))

2021-03-04 21:32 UTC, merged